### ISSUE TITLE
Keyword "your keyword" is bad!

### ISSUE THREAD

**Issue by RiccardoTr** [epfl-dlab/GoogleTrendsAnchorBank#10]
Hello,

I'm trying to analyze the trend of some keywords, but the output of the comand: _>>> query_1 = t.new_query("my_keyword")_
is: _Keyword my_keyword is bad!_

I think that the problem is the very low volume of these keywords. Is there any possibility to solve this issue?

Best wishes,

Riccardo

**Comment by GorjanP** [comment]
Dear Riccardo,

You are (unfortunately) correct! Some keywords simply do not have enough data to be useful, so the GoogleTrends API call returns an error.

Unfortunately, this is solely an issue on GoogleTrend's side and is not something that can be solved as is.
