### ISSUE TITLE
KeyError when creating anchorbanks

### ISSUE THREAD

**Issue by snorrefrid** [epfl-dlab/GoogleTrendsAnchorBank#11]
When building anchorbanks for certain regions and time periods, GTAB fails to execute completely due to a KeyError.

For example, when building an anchorbank for Romania in the period 2004-2020, GTAB reports the following error: 

```
Non-continuous groups at: 
['Google', '/m/0glpjll', 'Instagram', '/m/0mgkg', 'Amazon']
['/m/02y1vz', '/m/0glpjll', 'Instagram', '/m/0mgkg', 'Amazon']

KeyError: '/m/02y1vz'
```

The KeyError relates to the freebase code for Facebook. Perhaps it has something to do with Facebook first coming into existence later than 2004? I have tried removing Facebook from the list of high traffic queries in the config file, but still get this error, however.

--- 

Edit from @manoelhortaribeiro:

Code to replicate the error

~~~python

import gtab
t = gtab.GTAB()
t.set_options(pytrends_config={"geo": "RO", "timeframe": "2004-01-01 2020-12-31"})
t.create_anchorbank() # takes a while to run since it queries Google Trends.

~~~
`

**Comment by manoelhortaribeiro** [comment]
Hey @snorrefrid, sorry for the delay! I was able to replicate the issue you had and to find a quick fix:

- I fixed a small issue in the code where the pruning condition was too aggressive.
- I'm adding the word 'emag' (a popular website in Romania according to Alexa) in the query. This seems to do the job (as in, it is a query that is able to "connect" the two groups!

Here's the anchor bank

[google_anchorbank_geo=RO_timeframe=2004-01-01 2020-12-31.tsv.zip](https://github.com/epfl-dlab/GoogleTrendsAnchorBank/files/6249963/google_anchorbank_geo.RO_timeframe.2004-01-01.2020-12-31.tsv.zip)

I will update the code on the repo/pip soonish!

Happy easter


Ps: could you make the anchor banks that you crawled available to the community?
