### ISSUE TITLE
Aggregating Max_Ratio Values Together Across Search different search Queries

### ISSUE THREAD

**Issue by thebaker05** [epfl-dlab/GoogleTrendsAnchorBank#19]
Firstly I would like to wish you and your team a great big thank you. Your Google Trends Anchor Bank (Gtab) has been especially helpful, however, I have a question regarding your Project. 

I'll give you some background, so I am conducting a project on Google Search flight data on Behalf of a Travel Company I work for.

This is my [Google Collab Workflow. ](https://colab.research.google.com/drive/1nWfQtaRP3J0hs_NE5PYgJtVfdFXtYgzq#scrollTo=Ow2SGNHYwllp)

My Boss wants to know if it's possible to aggregate different search flight search terms even after the initial workflow has been executed. ( as long as the parameters of any later workflows are matched to this initial workflow e.g. t.set_options(pytrends_config={"geo": "GB", "timeframe": "2019-01-01 2021-11-23"}) is kept the same )

For example, starting with the query "flights Sri Lanka", and then keep adding at later dates according to the theme of "flights (destination)". For instance, adding the queries "flights to Sri Lanka" and then perhaps next "flights from UK to Sri Lanka". Therefore, he believes it's possible to simply add the Max_Ratio values from each query to get to this. Will this actually still be reflective in relation to how these search values in aggregate performed in google search in reality.  Or is there a problem with this approach? and in fact there may be a couple specifics we need to know about before pursing this course of action? 

Kind Regards,

Baker

**Comment by manoelhortaribeiro** [comment]
Hey Baker,

Not sure I entirely understand your question. But basically, **if you are using the same anchorbank, as you seem to be doing in your collab workflow**, you can safely "add" the max_ratio columns to get the sum of the search volume over multiple queries. 

If you do this per day, you get the total search volume for all the queries you added in that specific day, if you do this across multiple days, for example for an entire month, you get the whole search volume for that month.

The important part here is that you keep the same anchorbank. If you have an anchorbank A and happen to create a different anchorbank B, then search volume is not comparable between A and B!

Does that answer your question?

Best
Manoel

**Comment by thebaker05** [comment]
Thank you :)
