### ISSUE TITLE
Get data by month

### ISSUE THREAD

**Issue by chengzhix** [epfl-dlab/GoogleTrendsAnchorBank#21]
hi, may I get monthly google trends data in gtab？ not weekly

**Comment by manoelhortaribeiro** [comment]
Hey! So the granularity gtrends returns are a bit arbitrary and depend on the time-span. If you ask for a timeframe for many years, it automatically yields a monthly granularity, e.g., https://trends.google.com/trends/explore?date=all&geo=US&q=%2Fm%2F0dl567,%2Fm%2F0261x8t
