### ISSUE TITLE
US state or region level geo tags in pytrends_config?

### ISSUE THREAD

**Issue by LizMcQuillan** [epfl-dlab/GoogleTrendsAnchorBank#4]
Is there a way to pass a more granular `geo:` argument than the country level? Specifically, at the US state ("New York", "Kentucky", etc) or regional ("Northeast", "West", etc) levels?

Looking through your source code it looks like the answer is no (`geo (str) - containing the two-letter ISO code of the country, e.g. "US", or "" empty string for global`).

**Comment by manoelhortaribeiro** [comment]
Hey Liz! Indeed I feel that right now it is not (yet) supported, yet, I feel this can be made possible with minor changes @GorjanP, can you have a look at that?

**Comment by GorjanP** [comment]
Hi Liz! To directly address your question about US state level queries, it is indeed supported! The underlying Google Trends API is [PyTrends](https://pypi.org/project/pytrends/), and its documentation states:

> More detail available for States/Provinces by specifying additional abbreviations. For example: Alabama would be 'US-AL'

I am not sure if the Google Trends documentation has an explicit list, but one way to figure it out is to type a query into [Google Trends ](https://trends.google.com/trends/) and when choosing the region click the little arrow next to it to see the available sub-regions (see image).


![ex](https://user-images.githubusercontent.com/39885334/93268346-4e1abf00-f7ad-11ea-9081-e6aa2700ca4c.png)


After this notice that the URL in your browser window contains the abbreviation. For example If I choose `Austria -> Vienna`, the URL is `https://trends.google.com/trends/explore?geo=AT-9&q=Example%20query` and the geo code is there - `AT-9`. You just have to set it via the` set_options` method or if you're using the command line interface through `gtab-set-options` script.

N.B. The PyTrends official documentation explicitly states "two letter country abbreviation", hence why the G-TAB documentation does the same. To clear any future potential confusion I will try to extract all available regions from the Google Trends website and list them in the documentation. Thanks for noticing this!

**Comment by LizMcQuillan** [comment]
Thanks! It would be helpful to add a line in your docs saying that you support sub-country level queries - even with a link to the pytrends docs that govern the naming conventions.
