### ISSUE TITLE
Calibration across geographic areas

### ISSUE THREAD

**Issue by wanyi233** [epfl-dlab/GoogleTrendsAnchorBank#6]
Hi! Your package is very helpful to the project I’m working on! I do have one question though. It seems that I need to set a new anchor bank for each geographic area and time span, but if I want to compare google trends across different geographic area (e.g. country or U.S. states) over a given period, does your package support calibration across different areas?

**Comment by manoelhortaribeiro** [comment]
Hey @wanyi233! Unfortunately we do not support calibration across different areas (yet!) This is an interesting direction for extending our method.

**Comment by cervisiarius** [comment]
Thanks for the comment @wanyi233! I agree that this would be a super useful extension.
This paper might have some good ideas on how to go about it:
"[Lifestyle Disease Surveillance Using Population Search Behavior:Feasibility Study](https://ingmarweber.de/wp-content/uploads/2020/01/Lifestyle-Disease-Surveillance-Using-Population-Search-Behavior-Feasibility-Study.pdf)" by Memon, Razak, and Weber.
