### ISSUE TITLE
Volume of queries

### ISSUE THREAD

**Issue by RiccardoTr** [epfl-dlab/GoogleTrendsAnchorBank#8]
Hi! 

The anchor bank looks very helpful and interesting. I'm here to present a couple of questions. 

1) Is it possible to evaluate the volume of a given query in a given period of time and space? (I was running the examples, but the volume of 'facebook' query is lower than expected as showed in the example plot)

2) Is it possible to calculate the exact (or at least a reasonable) number of a given query in a specific amount of time? 

Best wishes!

**Comment by manoelhortaribeiro** [comment]
Hey Riccardo!

Maybe I misunderstood your questions, but yeah, that is what the library is for :)

On the difficulty of reproducing results, did you use the same time-frame as we did? Please post the exact code you used, images of the result you had, and how it is different from the example.

**Comment by RiccardoTr** [comment]
**Regarding the volume of queries:**
-How is it possible to calculate a correct value? Is it obtained usining the max_ratio?

**Regarding the example:**
-I used: 
>>>_import gtab_
>>> _t = gtab.GTAB()_
Using directory 'C:\Users\Lab\AppData\Local\Programs\Python\Python38\lib\site-packages\gtab'
Active anchorbank changed to: google_anchorbank_geo=_timeframe=2019-01-01 2020-08-01.tsv
>>> _query_facebook = t.new_query("facebook")_
Using C:\Users\Lab\AppData\Local\Programs\Python\Python38\lib\site-packages\gtab\output\google_anchorbanks\google_anchorbank_geo=_timeframe=2019-01-01 2020-08-01.tsv
New query 'facebook'
New query calibrated!
>>> _query_swaziland = t.new_query("swaziland")_
Using C:\Users\Lab\AppData\Local\Programs\Python\Python38\lib\site-packages\gtab\output\google_anchorbanks\google_anchorbank_geo=_timeframe=2019-01-01 2020-08-01.tsv
New query 'swaziland'
New query calibrated!
>>> _import matplotlib.pyplot as plt_
>>> _plt.plot(query_swaziland.max_ratio)_
[<matplotlib.lines.Line2D object at 0x0000021AA9A15730>]
>>> _plt.plot(query_facebook.max_ratio)_
[<matplotlib.lines.Line2D object at 0x0000021AABA57100>]
>>> _plt.show()

Here's the plot... non-informative at all :( 
![Figure_1](https://user-images.githubusercontent.com/72551093/95958929-1cbffe00-0e02-11eb-840f-156fbfbe534c.png)
_

**Comment by manoelhortaribeiro** [comment]
The plot is non-informative probably because the traffic of Swaziland is veeeery small compared to Facebook. 

I wonder how it would look like if you add this on log scale something like:

`plt.yscale("log")`

Like we did in the example!

Re: about estimating the total query volume in number of queries. You could try to get estimates with another service (e.g. google ads manager) and multiply these estimates by the number you find using our library!
